/* Description:
     * ============
     *  Test class for MyUtilityClass
     *
     * Author:
     * ========
     * Arun Balasubramanian
     *
     * Revision History:
     * =================
     * 05/29/2018 - Initial development built
*/
@isTest
private class TestMyUtilityClass{

    static testMethod void myTestMthod(){
       MyUtilityClass cl = new MyUtilityClass ();
       // Arun B added comment to test merge
    }

}